# Generated by Django 5.0 on 2026-06-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=10)),
                ('severity_level', models.CharField(choices=[('NONE', 'NONE'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL')], default='NONE', max_length=10)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('eld_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='upload.eldfile')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('check_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='validations.validationrun')),
            ],
        ),
        migrations.CreateModel(
            name='ChecksumResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_checksum', models.CharField(max_length=64)),
                ('actual_checksum', models.CharField(max_length=64)),
                ('is_valid', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checksums', to='validations.validationrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_ms', models.IntegerField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='validations.validationrun')),
            ],
        ),
    ]
