# Generated by Django 5.0 on 2026-06-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('expected_value', models.TextField(blank=True, null=True)),
                ('actual_value', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_validations', to='validations.validationrun')),
            ],
        ),
    ]
