# Generated by Django 5.0 on 2026-06-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0002_rulevalidationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_events', to='validations.validationrun')),
            ],
        ),
    ]
