# Generated by Django 5.0 on 2026-06-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0003_diagnosticevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalfunctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malfunction_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('escalated_from_diagnostic', models.BooleanField(default=False)),
                ('severity', models.CharField(default='critical', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malfunction_events', to='validations.validationrun')),
            ],
        ),
    ]
