# Generated by Django 5.0 on 2026-06-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_malfunctionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('affected_records', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='validations.validationrun')),
            ],
        ),
    ]
