# Generated by Django 5.0 on 2026-06-12 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0005_investigationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.CharField(max_length=20)),
                ('corrected_status', models.CharField(max_length=20)),
                ('errors_before', models.IntegerField(default=0)),
                ('errors_after', models.IntegerField(default=0)),
                ('warnings_before', models.IntegerField(default=0)),
                ('warnings_after', models.IntegerField(default=0)),
                ('compliance_score_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('compliance_score_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('change_log', models.JSONField(default=list)),
                ('before_after_comparison', models.JSONField(default=list)),
                ('corrected_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('final_verdict', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction_report', to='validations.validationrun')),
            ],
        ),
    ]
