# Generated by Django 5.0 on 2026-06-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0006_correctionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionreport',
            name='errors_remaining_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='correctionreport',
            name='revalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctionreport',
            name='validator_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='correctionreport',
            name='verification_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
