# Generated by Django 5.0 on 2026-06-10 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non-IT'), ('Finance', 'Finance')], max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('us_dot_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('license_plate', models.CharField(max_length=20)),
                ('power_unit_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmvs', to='upload.company')),
            ],
        ),
        migrations.CreateModel(
            name='ELDFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('overall_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant')], default='compliant', max_length=20)),
                ('raw_header_json', models.JSONField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('cmv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eld_files', to='upload.cmv')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ELDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.IntegerField()),
                ('record_status', models.IntegerField()),
                ('record_origin', models.IntegerField()),
                ('event_type', models.IntegerField()),
                ('event_code', models.IntegerField()),
                ('event_date_time', models.DateTimeField()),
                ('accumulated_engine_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('elapsed_miles', models.IntegerField(blank=True, null=True)),
                ('location_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('eld_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='upload.eldfile')),
            ],
        ),
    ]
