# Generated by Django 5.0 on 2026-06-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldfile',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eldfile',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
