# Generated by Django 5.0 on 2026-06-11 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validations', '0005_investigationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveAuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('llm_raw_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executive_audit', to='validations.validationrun')),
            ],
        ),
    ]
