# Generated by Django 5.0 on 2026-06-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveauditreport',
            name='remediation_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
